#!/bin/bash

set -eu

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" > /dev/null <<-EOSQL
  CREATE USER ${APP_USER};
  ALTER USER ${APP_USER} WITH PASSWORD '${APP_PASSWORD}';
  CREATE DATABASE ${APP_DB};
  GRANT ALL PRIVILEGES ON DATABASE ${APP_DB} TO ${APP_USER};
EOSQL
