version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/playground"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        # ignore patch updates
        update-types: [ "version-update:semver-patch" ]
