CREATE SCHEMA IF NOT EXISTS sandbox;
GRANT USAGE ON SCHEMA sandbox TO application;

ALTER DEFAULT PRIVILEGES IN SCHEMA sandbox GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO application;
ALTER DEFAULT PRIVILEGES IN SCHEMA sandbox GRANT USAGE, SELECT ON SEQUENCES TO application;
