name: 'playground-java'
services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MIGRATION_USER=flyway
      - MIGRATION_PASSWORD=flyway
      - APP_DB=playground
      - APP_USER=application
      - APP_PASSWORD=application
    volumes:
      - "$HOST_PG_DIR/conf:/etc/postgresql"
      - "$HOST_PG_DIR/init:/docker-entrypoint-initdb.d"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
  cache:
    image: "valkey/valkey:${VALKEY_VERSION}"
    ports:
      - "${VALKEY_PORT}:6379"
