name: 'playground-java'
services:
  sonarqube:
    build:
      dockerfile_inline: |
        FROM sonarqube:${SONAR_VERSION}
        USER root
        RUN apt-get update && apt-get -y install jq
        USER sonarqube
    ports:
      - "${SONAR_PORT}:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - "$HOST_SONAR_DIR:/healthcheck"
    healthcheck:
      test: 'bash /healthcheck/healthcheck.sh'
      interval: 10s
      timeout: 5s
      retries: 20

  sonarqube-init:
    image: "alpine/curl:8.10.0"
    command: ["/init/set-up-sonarqube.sh"]
    volumes:
      - "$HOST_SONAR_INIT_DIR:/init"
    depends_on:
      sonarqube:
        condition: service_healthy
