spring:
  profiles:
    active: local
  application:
    name: playground-java
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/playground
    username: application
    password: application
  jpa:
    hibernate:
      ddl-auto: none
  security:
    user:
      name: admin@basic
      password: admin

cache:
  valkey:
    cluster:
      enabled: false
    nodes:
      - localhost:6379
    min-idle: 16

management:
  endpoints:
    web:
      # Change /actuator endpoints to /. (e.g. /actuator/health -> /health)
      base-path: /
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        security: INFO
