spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/playground
    username: application
    password: application

  jpa:
    hibernate:
      ddl-auto: none
