name: playground CI

on:
  push:
    branches:
      - main
    paths:
      - playground/*
#  pull_request:
#    branches:
#      - main
#    paths:
#      - playground/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
      - name: Run tests
        run: ./gradlew test
        working-directory: playground/
